### ISSUE TITLE
Add support for a WYSIWYG editor

### ISSUE THREAD

**Issue by enkota** [poowf/otter#17]
It would be good to add in some support for a WYSIWYG text editor when using the interface for blogging. 

Some good editors to use would be:

https://alex-d.github.io/Trumbowyg/ 

https://summernote.org

Thanks!

**Comment by earboxer** [comment]
Right now, it appears that editor interfaces are defined by `resources/assets/js/components/FormComponent.vue`.

Is the plan to keep using vue for this? I'd love to help, but I haven't familiarized myself with vue.

**Comment by zanechua** [comment]
@earboxer 

Yes. 

It is my intention that the UI components in this package are all handled via Vue Components.

By custom appearance do you mean CSS classes? If so, could you create a separate issue for that?

**Comment by earboxer** [comment]
I was thinking of having 'textarea' create a `<textarea>` instead of `<input type='textarea'>`.

(As far as CSS styling, currently, one could just write a style that was `input[type=textarea]` if they just wanted to change the style based on the different type...)

**Comment by zanechua** [comment]
textarea  and select are the only components that require this I think. 

We can just add logic to the component to check for that.

**Comment by earboxer** [comment]
Sounds good. I have a branch (https://github.com/earboxer/otter/tree/textarea) that does this. But I targeted it at master. I might be able to work on rebasing it on development, but there are some merge conflicts I'm not sure how to resolve.

**Comment by earboxer** [comment]
While my merge request just adds logic in the component, I think we might want a more extensible framework for adding new field types (so that people can get their own custom fields types without having to make changes to otter). I'm going to open an issue soon with a proposal for this, so as to avoid hijacking this thread.

**Comment by zanechua** [comment]
The Trumbowyg editor was added in https://github.com/poowf/otter/commit/5cd2134fc54823ada964c0d1d32a4b35d5276b01 with some sensible defaults.

You just need to add the type of `wysiwyg` to your OtterResource file and it should render accordingly

**Comment by zanechua** [comment]
Doh. Me being me. Totally slipped my mind that trumbowyg doesn't play well with v-model and therefore it doesn't update the data. I have something in the works but for now, the wysiwyg works for viewing html data.

**Comment by zanechua** [comment]
Okay. This commit should fix the updating, tested it locally and all seems to be good.

Might have to revisit the implementation of this when we get to #45 .

Finished in https://github.com/poowf/otter/commit/6d65acd5cae30c06d9173ac611b988607369c488
