### ISSUE TITLE
Resource namespace can not be changed properly

### ISSUE THREAD

**Issue by koenhoeijmakers** [poowf/otter#20]
Currently it seems possible to set the `Otter::$otterResourceNamespace` to a different namespace to your liking. 

But when the names of the resources are collected in `Otter::getResourceNames()` it wrongly declares `app_path('Otter/')` which means that if i was to change the namespace, it would find none as it checks default namespace.

**Comment by zanechua** [comment]
That variable was actually not intended to be changed but since it's in there, I think I'll switch it to a configuration variable instead as it makes more sense to pull from a central location versus having to define it in all the OtterResources

**Comment by zanechua** [comment]
Resolved in:
https://github.com/poowf/otter/commit/452dcabf745f9cdcbc1b870b04b791609c16d2dc

Temporarily still keeping it as a static variable. Possibly add a configuration value in the future for namespace changes but for now would prefer it to be kept to App/Otter for consistency purposes.
