### ISSUE TITLE
Uninstantiable class bound to container?

### ISSUE THREAD

**Issue by koenhoeijmakers** [poowf/otter#21]
It seems that you are binding the `Otter` class to the container and then use it as a facade. I don't see the use of this as:
A. The Otter class will never be an instance, its a collection of methods.
B. The idea of a facade is "to resolve an instance from the container and be able to directly call methods on that instance" (i'm not that fond of facades but to each their own)

This can be solved in multiple ways like either making the class instantiable (and thus not so static) or you could refrain binding the class to the container and let people use the static `Otter` class directly.

**Comment by zanechua** [comment]
Yeah. I started off with some defaults and Facades was one of them. Further down the chain, I realised that there's no use for the Otter Facade but I left it there. Will probably just point it to the static Otter class.

**Comment by zanechua** [comment]
Resolved in:
https://github.com/poowf/otter/commit/452dcabf745f9cdcbc1b870b04b791609c16d2dc
