### ISSUE TITLE
Unable to install due an error

### ISSUE THREAD

**Issue by ronaldrios** [poowf/otter#28]
D:\www\admin>composer require poowf/otter
Using version dev-master for poowf/otter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing poowf/otter (dev-master f760c6d): Cloning f760c6d5f4 from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Finder.php line 581:

  The "D:\www\admin\app\Otter/" directory does not exist.

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by zanechua** [comment]
Is this Windows?

**Comment by ronaldrios** [comment]
Windows 10

**Comment by zanechua** [comment]
@ronaldrios 

Can you try the latest version? It should be fine now.

**Comment by ronaldrios** [comment]
I will try ir. Thanks

**Comment by ronaldrios** [comment]
Indeed. It is working now. Thanks a lot.

 �

**Comment by zanechua** [comment]
Fixed in:
https://github.com/poowf/otter/commit/0abb36f2f7505424996fbfad7a77251698649bf8
