### ISSUE TITLE
Provide some demo

### ISSUE THREAD

**Issue by mehi-shokri** [poowf/otter#31]
Having a demo would greatly help at grasping the librariy

**Comment by zanechua** [comment]
What kind of demo do you need?

**Comment by mehi-shokri** [comment]
Nope, a simple CRUD app with likely 3 to 4 models. 
Then show the otter panel working on top of it hosted live.

**Comment by zanechua** [comment]
Sorry. I don't think I have the capacity to set-up and maintain such a demo at the moment. 

The most I can do is make a step-by-step guide or write an article about it for now.

Will take this into consideration for future implementation.

Thank you for your suggestion

**Comment by mehi-shokri** [comment]
Maybe I can help?

**Comment by zanechua** [comment]
@mehi-shokri 

Sure. If you would like to host an example. I can put it in the readme.

**Comment by mehi-shokri** [comment]
No problem. Will take a look at it whenever I can. will try to create a simple laravel app with otter on top of it showing how it can help with. 
But I give no time estimates

**Comment by zanechua** [comment]
No worries!

Just comment back and ping me incase I miss it.
