### ISSUE TITLE
Values have whitespace trimmed off of them

### ISSUE THREAD

**Issue by earboxer** [poowf/otter#44]
One issue with this (and maybe with fields in otter in general) is that if trailing and preceding whitespace gets trimmed off of anything you try to save.

I assume that's unintentional: if any modification should happen, it should be defined in the eloquent Model as a [mutator](https://laravel.com/docs/5.8/eloquent-mutators#defining-a-mutator).

_Originally posted by @earboxer in https://github.com/poowf/otter/pull/42#issuecomment-482776417_

**Comment by zanechua** [comment]
Just thinking from memory sake, I don't recall trimming any strings. This is actually handled in Laravel by one of the middlewares introduced in Laravel 5.4. The "TrimStrings" Middleware.
